provider "aws" {
  region = var.aws_region
}

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
        source = "hashicorp/aws"
        version = "~>5.60"
    }
  }
}

# token - Authentication token generated by the AWS
# for the IAM identity running Terraform.
provider "helm" {
    kubernetes = {
      host = data.terraform_remote_state.eks.outputs.endpoint
      cluster_ca_certificate = base64decode(data.terraform_remote_state.eks.outputs.ca)
      token = data.aws_eks_cluster_auth.eks.token
    }
}

module "metrics-server" {
  source = "../../../modules/addons/metrics-server"
}

module "cluster-autoscaler" {
  source = "../../../modules/addons/cluster-autoscalar"
  eks_cluster_name = data.terraform_remote_state.eks.outputs.eks_cluster_name
}

module "argocd" {
  source = "../../../modules/addons/argocd"
}

module "argocd-image-updater" {
  source = "../../../modules/addons/argocd-image-updater"
  eks_cluster_name = data.terraform_remote_state.eks.outputs.eks_cluster_name
}


module "secrets_csi" {
  source = "../../../modules/addons/secrets_csi_driver"
}